"""Store port: the interface every storage backend implements.

InMemoryStore (default, zero-dependency) and PostgresStore both satisfy this,
so services and routes never depend on a concrete backend.
"""
from __future__ import annotations

from typing import Protocol


class Store(Protocol):
    def save_session(self, session_id: str, name: str) -> None: ...
    def save_events(self, session_id: str, events: list) -> None: ...
    def load_events(self, session_id: str) -> list: ...
    def save_graph(self, graph, session_id: str) -> None: ...
    def get_graph(self, workflow_id: str): ...
    def session_for(self, workflow_id: str) -> str: ...
    def list_workflows(self) -> list: ...
    def save_run(self, run: dict) -> None: ...
    def get_run(self, run_id: str): ...
    def list_runs(self, workflow_id: str) -> list: ...
